# Generated by Django 3.0 on 2019-12-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_serverr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='passs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pas', models.CharField(max_length=20)),
            ],
        ),
    ]
